# Alacritty config

[general]
import = [
	"themes/tokyo-night-storm.toml",
]

[font]
normal = { family = "Comic Code", style = "Regular" }
size = 15.0

[window]
dimensions = { columns = 80, lines = 24 }
padding = { x = 36, y = 36 }
