plugins:
  - inline # for defining custom fields

item_fields:
  disc_and_track: u'%i-%02i' % (disc, track) if disctotal > 1 else u'%02i' % (track)

directory: /tmp/music

# Define the default file path.
paths:
  default: $albumartist/$year $album%aunique{}/$disc_and_track $title
asciify_paths: yes
per_disc_numbering: yes
# Replace some segments of filenames.
replace:
  '_': ''
