library: "~/.cache/beets/library.db"
directory: "~/Music/.beets"

# Plugins {{{

# Plugins to enable,
# see https://beets.readthedocs.io/en/stable/plugins/index.html for details.
plugins: [
  "fetchart",
  "hook",
  "rewrite",
]

fetchart:
  auto: yes # auto-fetch during import
  cautious: yes # pick those with correct filenames only
  cover_names: cover front # names that are considered "correct"
  minwidth: 1000 # only accept 1000px and higher resolution
  enforce_ratio: yes # only accept width:height=1:1 ratio
  sources: filesystem itunes coverart albumart # sources to look for, local first
  high_resolution: yes # storage is cheap, fetch highest resolution possible

hook:
  hooks:
    - event: album_imported
      command: echo "{album.path}"

rewrite:
  artist .*Art Blakey.*: Art Blakey
  artist .*Oscar Peterson.*: Oscar Peterson
  artist .*Prince.*Revolution.*: Prince
  artist .*Velvet Underground.*: Velvet Underground

# }}}

# Ignore some bad paths, this including the infamous SVI directories
# that Windows shit everywhere it can, and the 'lost+found' directory created by fsck.
ignore: [ "System Volume Information", "lost+found" ]
ignore_hidden: yes

# Replace some characters in path and sadly, not in metadata.
replace:
  "_": ""

# Handle different releases with the same names by same artists.
# Check the release years and labels, for both albums (including EPs) and singletons.
aunique:
  keys: albumartist album
  disambiguators: albumtype year label albumdisambig
  bracket: "()"
sunique:
  keys: artist title
  disambiguators: year label trackdisambig
  bracket: "()"

# Define the default file path.
paths:
  default: $albumartist/[$original_year] $album%aunique{}/$track $title

import:
  move: yes # move files instead of copying
