plugins: [
  "fetchart",
  "filetote",
]

fetchart:
  cautious: yes # pick those with "correct" filenames only
  cover_names: album cover folder front # names considered "correct"
  minwidth: 1000 # only accept 1000px and higher resolution
  enforce_ratio: yes # only accept width:height=1:1 ratio
  sources: filesystem coverart itunes albumart # sources to look for
  high_resolution: yes # storage is cheap, fetch highest resolution possible

filetote:
  extensions: [
    ".cue", # import cuesheets
    ".log", # import log files
  ]
  pairing:
    enabled: true # import "name.*" files along with "name.music_ext"
  paths:
    ext:.cue: "$albumpath/$album" # rename cuesheets
    ext:.log: "$albumpath/$album" # rename log files
