library: "~/.cache/beets/library.db"
directory: "~/Music/.beets"

# Plugins {{{

# Plugins to enable,
# see https://beets.readthedocs.io/en/stable/plugins/index.html for details.
plugins:
  - advancedrewrite
  - fetchart
  - hook

advancedrewrite:
  - match: "’"
    replacements: 

fetchart:
  auto: yes # auto-fetch during import
  cautious: yes # pick those with correct filenames only
  cover_names: cover front # names that are considered "correct"
  minwidth: 1000 # only accept 1000px and higher resolution
  enforce_ratio: yes # only accept width:height=1:1 ratio
  sources: filesystem itunes coverart albumart # sources to look for, local first
  high_resolution: yes # storage is cheap, fetch highest resolution possible

hook:
  hooks:
    - event: import
      command: echo "{paths}"

# }}}

# Define the default file path.
paths:
  default: $albumartist/[$originalyear] $album%aunique{}/$track $title
asciify_paths: yes
# Replace some segments of filenames.
replace:
  '_': ''
