include: "config-plugins.yaml"

# Set the directory hierarchy.
paths:
  default: "$albumartist/[$original_year] $album%aunique{}/$track $title"
  singleton: "$artist/#Singles/[$original_year] $title/$track $title"
  comp: "#VariousArtists/[$original_year] $album%aunique{}/$track $title"
