# alacritty configuration file

import = [
	"~/.config/alacritty/themes/tokyo-night-storm.toml"
]

shell = "/usr/bin/bash"

[window]
dimensions = { columns = 80, lines = 24 }
padding = { x = 32, y = 32 }
dynamic_padding = true

[font]
normal      = { family = "OperatorMono Nerd Font Mono", style = "Regular" }
italic      = { family = "OperatorMono Nerd Font Mono", style = "Italic" }
bold        = { family = "OperatorMono Nerd Font Mono", style = "Bold" }
bold_italic = { family = "OperatorMono Nerd Font Mono", style = "Bold Italic" }

size = 15
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

builtin_box_drawing = true

