# Polybar version 3.7.1, theme "darktide".
# Requires picom for transparency.

# Inspired by the post
# https://www.reddit.com/r/unixporn/comments/17onrtz/i3_polybar_everforest/
# of reddit user @Astonish_Skagen.



# Define modules in separate file.
include-file = ./modules.ini

# Set colors.
[colors]
foregr = #CAF0F8
fg-alt = #ADE8F4
backgr = #77313131
bg-alt = #77414141
primry = #00B4D8
second = #0077B6
urgent = #FF595E
# Ocean Blue gradients.
grad-1 = #0096C7
grad-2 = #00789F
grad-3 = #005A77


[bar/foobar]
# Enable IPC to receive quit messages.
enable-ipc = true
# Tell i3 not to lock the bar position. Need manually set top gap.
override-redirect = true
# Tell i3 to put the bar below all windows for fullscreens.
wm-restack = i3

# Positions
offset-x = 2%
offset-y = 8px

# Shapes
width = 96%
height = 32px
radius = 8px

# Colors
foreground = ${colors.foregr}
background = ${colors.backgr}

# Fonts
font-0 = Operator Mono:size=15:style=Bold;3
font-1 = Material Design Icons Desktop:size=18;4

# Modules
modules-left = arch i3-ws
#modules-center = grad-l-3 grad-l-2 grad-l-1 datime grad-r-1 grad-r-2 grad-r-3
#modules-right = cpu filesystem wlan battery droptray power
modules-right = power

