# Polybar version 3.7.1, theme "darktide".
# Requires picom for transparency.

# Inspired by the post
# https://www.reddit.com/r/unixporn/comments/17onrtz/i3_polybar_everforest/
# of reddit user @Astonish_Skagen.



# Define modules in separate file.
include-file = ./modules.ini

# Set colors.
[colors]
backgr = #24283B
bg-alt = #3B4261
foregr = #C0CAF5
fg-alt = #a9B1D6
primry = #7AA2F7
second = #3D59A1
urgent = #FF757F



[bar/foobar]
# Enable IPC to receive quit messages.
enable-ipc = true
# Tell i3 not to lock the bar position. Need manually set top gap.
override-redirect = true
# Tell i3 to put the bar below all windows for fullscreens.
wm-restack = i3

# Positions
offset-x = 2%
offset-y = 8px

# Shapes
width = 96%
height = 32px
radius = 8px

# Colors
foreground = ${colors.foregr}
background = ${colors.backgr}

# Fonts
font-0 = "Operator Mono:size=15:style=Bold;3"
font-1 = "Material Design Icons Desktop:size=18;4"

# Modules
modules-left = arch i3-ws
modules-right = cpu filesystem pulseaudio wlan time battery power

