# Polybar Modules

### Arrr-ch! {{{

[module/arch]
type = custom/text

format = "󰣇"
format-foreground = #1793D1
format-padding = 1

[module/power]
type = custom/text

format = "󰐥"
format-foreground = ${colors.urgent}
format-padding = 1

### }}}

### Battery {{{

[module/battery]
type = internal/battery
# Use the following command to list adapters and batteries:
#   $ ls -1 /sys/class/power_supply/
adapter = "AC"
battery = "BAT1"

# If an inotify event haven't been reported in this many
# seconds, manually poll for new values, default is 5.
poll-interval = 5

format-charging = "󰂄%{O4px}<label-charging>"
format-charging-foreground = ${colors.primry}
format-charging-padding = 1

label-charging = "%percentage%%"
label-charging-foreground = ${colors.foregr}

format-discharging = "<ramp-capacity>%{O4px}<label-discharging>"
format-discharging-padding = 1

ramp-capacity-0 = "󰂎"
ramp-capacity-0-foreground = ${colors.urgent}
ramp-capacity-1 = "󰁻"
ramp-capacity-1-foreground = ${colors.primry}
ramp-capacity-2 = "󰁽"
ramp-capacity-2-foreground = ${colors.primry}
ramp-capacity-3 = "󰁿"
ramp-capacity-3-foreground = ${colors.primry}
ramp-capacity-4 = "󰂁"
ramp-capacity-4-foreground = ${colors.primry}
ramp-capacity-5 = "󰁹"
ramp-capacity-5-foreground = ${colors.primry}

label-discharging = "%percentage%%"
label-discharging-foreground = ${colors.foregr}

format-full = "󰁹%{O4px}<label-full>"
format-full-foreground = ${colors.primry}
format-full-padding = 1

label-full = "%percentage%%"
label-full-foreground = ${colors.foregr}

### }}}

### CPU {{{

[module/cpu]
type = internal/cpu

# Seconds to sleep between updates, default is 1.
interval = 0.5

# Emit warning signal when CPU load reaches the value, default is 80.
warn-percentage = 90

# Format to show, default is <label>.
format = "<label>"
format-prefix = "󰍛%{O4px}"
format-prefix-font = 5
format-prefix-foreground = ${colors.primry}
format-padding = 12px

label = "%percentage%%"

# Format to show for warnings, default is <label-warn>.
format-warn = "<label-warn>"
format-warn-prefix = "󰍛%{O4px}"
format-warn-prefix-font = 5
format-warn-prefix-foreground = ${colors.urgent}
format-warn-padding = 12px

label-warn = "%percentage%%"

### }}}

### Date & Time {{{

[module/time]
type = internal/date

# Seconds to sleep between updates.
interval = 1.0

format = "󰅐%{O4px}<label>"
format-foreground = ${colors.primry}
format-padding = 1

label = "%time%"
label-foreground = ${colors.foregr}

# Clicking on the module will toggle between formats.
time = "%H:%M"
time-alt = "%H:%M:%S"

### }}}

### Filesystem {{{

[module/filesystem]
type = internal/fs
# Mountpoints to display, default is /.
mount-0 = /

# Seconds to sleep between updates, default is 30.
interval = 10.0

# Display fixed precision values, default is false.
fixed-values = true
# Warns when usage exceeds, default is 90.
warn-percentage = 80

# Format to show for mounted paths, default is <label-mounted>.
format-mounted = "<label-mounted>"
format-mounted-prefix = "󰑹%{O4px}"
format-mounted-prefix-font = 4
format-mounted-prefix-foreground = ${colors.primry}
format-mounted-padding = 12px

label-mounted = "%percentage_free%%"

### }}}

### Network {{{

[module/wlan]
type = internal/network
# If interface is empty, polybar will choose the interface automatically.
interface = ""
interface-type = "wireless"
# Seconds to sleep between updates, default is 1.
interval = 3.0

format-connected = "<ramp-signal>%{O4px}<label-connected>"
format-connected-padding = 1

ramp-signal-0 = "󰤯"
ramp-signal-1 = "󰤟"
ramp-signal-2 = "󰤢"
ramp-signal-3 = "󰤥"
ramp-signal-4 = "󰤨"
ramp-signal-foreground = ${colors.primry}

label-connected = "%essid%"
label-connected-foreground = ${colors.foregr}

format-disconnected = "󰤮" 
format-disconnected-foreground = ${colors.urgent}
format-disconnected-padding = 1

### }}}

### Volume {{{

[module/pulseaudio]
type = internal/pulseaudio

format-volume = "<ramp-volume>%{O4px}<label-volume>"
format-volume-padding = 1

ramp-volume-0 = "󰕿"
ramp-volume-1 = "󰖀"
ramp-volume-2 = "󰕾"
ramp-volume-foreground = ${colors.primry}

label-volume = "%percentage%%"
label-volume-foreground = ${colors.foregr}

format-muted = "󰖁"
format-muted-foreground = ${colors.urgent}
format-muted-padding = 1

### }}}

### Workspaces {{{

[module/i3-ws]
type = internal/i3

format = "<label-state>"
format-padding = 3

label-focused = "%index%"
label-focused-foreground = ${colors.primry}
label-focused-background = ${colors.bg-alt}
label-focused-padding = 1

label-unfocused = "%index%"
label-unfocused-foreground = ${colors.second}
label-unfocused-padding = 1

label-visible = "%index%"
label-visible-foreground = ${colors.second}
label-visible-padding = 1

label-urgent = "%index%"
label-urgent-foreground = ${colors.urgent}
label-urgent-padding = 1

### }}}

